
\section{Bacteria}
We reanalyze data we used already in the last project day.
In an experiment on nutrients on bacterial growth,
bacteria were grown in different media with the nutrients sucrose and leucine added.
After fours days the numbers of bacteria, \verb+density+, were counted.
<<>>=
library(LiSciData)
data(bactsucrose)
@

\begin{enumerate}
\item
Assume the responses \verb+density+ to be normally distributed.
Assume the predictors \verb+day+, \verb+sucrose+ and \verb+leucine+ as factors.
Consider  a model which is  additive in \verb+day+ and with an interaction between the other two
factors.  
Which link function would the Box-Cox approach suggest?
\item
Fit the corresponding model  using the identified link assuming the data to be normally distributed.
\item
We want to identify an appropriate variance function.
Take the absolute residuals \verb+abs(res)+ (on the response scale) from the above model 
and the predicted values \verb+fit+ (on the response scale) and fit the linear model
\[
E(\log(|res|))= \phi + \lambda \log (fit)
\]
Twice the slope of the fitted equation will give the exponent $\lambda$ in the variance function
\[
V(\mu)= \phi \mu^\lambda
\]
\item
Use the estimated $2 \cdot \lambda$ to propose a different distribution for the observations. Fit this new model.
\item
Check whether you still need the interaction between sucrose and leucine.
\item
Fit two models with the \verb+log+ link assuming either normally or gamma distributed data.
Use AIC and cross-validation to decide which model to choose.

\end{enumerate}


\begin{solution}
<<fig=F,results=hide>>=
bactsucrose<-transform(bactsucrose,y=density/max(density),day=factor(day),sucrose=factor(sucrose),leucine=factor(leucine))
library(MASS)
boxcox(y~day+sucrose+leucine+sucrose:leucine,data=bactsucrose)
m.normal.log<- glm(density~day+sucrose+leucine+sucrose:leucine,data=bactsucrose,family=gaussian(link=log))
res<-residuals(m.normal.log,type='response')
fit<-predict(m.normal.log,type='response')
g<-glm(log(abs(res))~log(fit))
m.normal.log<- glm(density~day+sucrose+leucine+sucrose:leucine,data=bactsucrose,family=gaussian(link=log))
m.gamma.log<-glm(density~day+sucrose+leucine+sucrose:leucine,data=bactsucrose,family=Gamma(link=log))
library(boot)
AIC(m.normal.log)
AIC(m.gamma.log)
cv.glm(bactsucrose,m.normal.log)$delta
cv.glm(bactsucrose,m.gamma.log)$delta
@

\end{solution}

 
