---
title: "cov_structure"
author: "Søren Højsgaard"
format: 
  html:
    toc: true
    html-math-method: mathjax
    self-contained: true
vignette: >
  %\VignetteIndexEntry{cov_structure}
  %\VignettePackage{mixedup}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=!TRUE, size="footnotesize", warning = FALSE, message = FALSE, fig.height=2.5)
options("digits"=4)
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
options("width"=120)
```

## Introduction

This is a technical note illustrating methods for linear mixed models fitted with `lme`, `gls`, and `lmer` functions in R. 


## Packages used here

```{r}
library(mixedup)
library(doBy)
library(lme4)
library(nlme)
library(ggplot2)
library(broom.mixed)
source("cov_structure.R")
```


## Shoes data

```{r}
dat <- doBy::shoes
dat$footA <- NULL
dat <- dat |> 
  tidyr::pivot_longer(cols = c("A", "B"), names_to = "material", values_to = "wear") 
dat |> head()


formula. <- ~material|boy
data. <- dat

source("cov_structure.R")
bb <- block_ri(~boy, data=dat)
##bb <- block_ri(~1|boy, data=dat) ## BEDRE?
bb

aa <- bb$ZGZt

bb <- as.blockmatrix(as_character_matrix(aa))
val <- bb$value
bb$value <- NULL

bb2 <- lapply(bb, as_sym)
bb2$value <- val



bb[[11]]

bb |> length()





```

```{r}
lmm1 <- lmer(wear ~ material + (1|boy), data=dat, REML=F)
lme1 <- lme(wear ~ material, random = ~1|boy, data=dat, method="ML")
gls1 <- gls(wear ~ material, corCompSymm(form= ~1|boy),
           method="ML", data = dat)
```
