\section{Bacteria}

\begin{topics}
  Linear normal model; log-transformation.
\end{topics}

In an experiment on nutrients on bacterial growth,
bacteria were grown in different media with the nutrients sucrose and leucine added.
After fours days the numbers of bacteria, \verb+density+, were counted.
<<>>=
data(bactsucrose, package="LiSciData")
head(bactsucrose)
@

\begin{enumerate}
\item Assume the responses to be normally distributed and use an
  identity link.  Assume the predictors \verb+day+, \verb+sucrose+ and
  \verb+leucine+ as factors.  Fit a model which is additive in
  \verb+day+ and with an interaction between the other two factors.

\item
Look at the residuals. What do you observe?
\item

  Fit the model, where you assume that the transformed observations
\verb+log(density)+ are normally distributed.
Look at the residuals.

\end{enumerate}
