---
title: "Vignette for lm_bayes"
author: "Søren Højsgaard"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::knitr}
  %\VignetteIndexEntry{Vignette for lm_bayes}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(lmbayes)
library(broom)
library(cowplot)
library(ggplot2)
library(dplyr)
```


```{r}
y <- as.numeric(Nile)
asw <- factor(c(rep(0, 30), rep(1, length(y)-30)))
tvar <- (1871:1970)-1871
dat <- data.frame(y, asw, tvar) |> as_tibble()
dat |> head()
dat |> tail()
dat |> ggplot(aes(tvar, y)) + geom_point()
```


Want to fit models to increasingly larger sets of data:

```{r}
tt1 <- 35
tt2 <- 50
dat2 <- dat |> filter(tvar < tt1)
dat3 <- dat |> filter(tvar >= tt1 & tvar < tt2)
dat4 <- dat |> filter(tvar < tt2)
```

```{r}
form <- y ~ asw
dat2

lm1 <- lm(y~asw, data=dat)
lm1 |> sigma()
lm1 |> vcov()

prior <- list(m=c(1000, 0), C=diag(500, 2), sd=100)
fit2 <- lmb(form, data=dat2, prior=prior)
fit2

fit2 |> coef()
fit2 |> vcov()
fit2 |> sigma()
fit2 |> tidy()

lm1  <- as_lm(fit2)
lm1
lm1 |> coef()
lm1 |> vcov()
lm1 |> sigma()
lm1 |> tidy()

fit3 <- lmb(form, data=dat3, prior=fit2$posterior)
fit4 <- lmb(form, data=dat4, prior=fit2$prior)

fit2 |> coef()
fit3 |> coef()
fit4 |> coef()

fit2 |> vcov()
fit3 |> vcov()
fit4 |> vcov()

fit2 |> sigma()
fit3 |> sigma()
fit4 |> sigma()



dat_ <- cbind(dat, predint(fit2, newdata=dat))
pl <- dat_ |> ggplot(aes(tvar, y)) +
    geom_point() +
    geom_line(aes(y=pred), col="red") +
    geom_errorbar(aes(ymin=lwr, ymax=upr), width=.2,
                  alpha=.3,
                  position=position_dodge(0.05)) +
    geom_vline(xintercept = tt1)
pl

```

Plot for a range of datasets:

```{r}

prior  <-  list(m=c(1000, 0), C=diag(500, 2), sd=10)
tt.vec <- seq(5, 85, by=10)
plist  <- NULL
for (tt in tt.vec){
    dat2_ <- dat |> filter(tvar < tt)
    fit_  <- lmb(form, data=dat2_, prior=prior)
    dat_  <- cbind(dat, predint(fit_, newdata=dat))
    pl <- dat_ |> ggplot(aes(tvar, y)) +
        geom_point() +
        geom_line(aes(y=pred), col="red") +
        geom_errorbar(aes(ymin=lwr, ymax=upr), width=.2,
                      alpha=.1, position=position_dodge(0.05)) +
        geom_vline(xintercept = tt,) +
        ylim(c(400, 1400)) 
    plist <- c(plist, list(pl))
}

plot_grid(plotlist = plist)
```

