```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(caracas)
library(knitr)
library(pbkrtest)
library(broom.mixed)
library(Matrix)
```

```{r}
data(Orthodont, package="nlme")

data(shoes, package="doBy")
shoes0 <- doBy::shoes[1:4,]
shoes0 |> kable()
```

```{r}
shoes_long <-
    shoes0 |> pivot_longer(cols=c("A", "B"),
                           names_to="type", values_to = "wear")
shoes_long <- na.omit(shoes_long)
shoes_long |> head() |> kable()
```

```{r} 
shoes_long |> ggplot(aes(boy, wear, color=type)) + geom_point()
```

```{r}
fit1  <- lmer( wear ~ type + (1|boy), data=shoes_long )
fit0  <- update(fit1, .~. - type)
```

```{r}
Mv <- function(x, entry="v") {
    if (is_sym(x) && symbol_is_matrix(x)) {
        b <- vector_sym(ncol(x), entry=entry)
        return(x %*% b)        
    }
    if (is.numeric(x)) {
        return(vector_sym(x, entry=entry))        
    }
}

Mv2 <- function(x, entry="v") {
    if (is_sym(x) && symbol_is_matrix(x)) {
        b <- vector_sym(ncol(x), entry=entry)
        return(list(x, b))
    }
    if (is.numeric(x)) {
        return(vector_sym(x, entry=entry))        
    }
}

```

```{r}
formula(fit1, fixed.only=TRUE)
formula(fit1, random.only=TRUE)
model.matrix(fit1)

aa <- lFormula(fit1, data=shoes_long)
aa$X
aa$reTrms$Zt

fit1@call$data

fit1 |> get_SigmaG()

Zt <- fit1 |> getME("Zt")
X <- fit1 |> getME("X")


ZZ <- t(Zt)

GG <- function(tau2, nr){
    diag(tau2, nr)
}

RR <- function(sigma2, nr){
    diag(sigma2, nr)
}

yy <- 1:nrow(ZZ)

GG(.1, ncol(ZZ))
RR(.3, nrow(ZZ))

VV <- function(th1, th2, ZZ) {
    out <- ZZ %*% GG(th1, ncol(ZZ)) %*% t(ZZ) + RR(th2, nrow(ZZ))
    out
}

VV(.1, .4, ZZ)

detVV <- det(as.matrix(VV))

XX <- model.matrix(fit1)

VVi <- solve(VV)

bbhat <- solve(t(XX) %*% VVi %*% XX, t(XX) %*% VVi) %*% yy
bbhat

resid <- yy - XX %*% bbhat 

(1 / sqrt(detVV)) * exp(-0.5 * t(resid) %*% VVi %*% resid)


fit1 |> getME("Ztlist")
vc <- fit1 |> VarCorr()

Z <- t(as.matrix(Zt))

ZZZ <- Z %*% t(Z) * vc$boy[1,1]

II <- diag(1, nrow=nrow(Z)) * attr(vc, "sc")^2

ZZZ + II
sigma(fit1)


##
## Linear mixed model
##
## y = Xb + Zu + e
##
## u ~ N(0, G), e ~ N(0, R), begge diag
##
## Then var(y) = ZGZ' + R


shoes_long <- data.frame(
  stringsAsFactors = FALSE,
  footA = c("L", "L", "L", "L", "R", "R", "L", "L"),
  type = c("A", "B", "A", "B", "A", "B", "A", "B"),
  wear = c(13.2, 14, 8.2, 8.8, 10.9, 11.2, 14.3, 14.2),
  boy = as.factor(c("1", "1", "2", "2", "3", "3", "4", "4")))

yy <- shoes_long$wear
XX <- model.matrix(~type, data=shoes_long) |> head(10)
ZZ <- model.matrix(~-1+boy, data=shoes_long) |> head(10)
yy; XX; ZZ


yy_ <- as_sym(yy)
XX_ <- as_sym(XX)
ZZ_ <- as_sym(ZZ)

GG_ <- diag_("tau2", ncol(ZZ))
RR_ <- diag_("sigma2", nrow(ZZ))
VV_ <- ZZ_ %*% GG_ %*% t(ZZ_) + RR_ # var(y)
VVi_ <- solve(VV_)

## b for known value of variance
bb_ <- solve(t(XX_) %*% VVi_ %*% XX_, t(XX_) %*% VVi_) %*% yy_
bb_ <- bb_ |> simplify()
bb_

resid_ <- yy_ - XX_ %*% bb_
resid_

QQ_ <- t(resid_) %*% VVi_ %*% resid_
QQ_ <- QQ_  |> simplify()

detVV_ <- do_la(VV_, "det") ## Hvorfor mon det ikke lige virker?

## Profil likelihood
logL_ <- -0.5 * detVV_ - 0.5 * QQ_
logL_func <- as_func(logL_, vec_arg = T)
optim(c(.1, .1), logL_func, control=list(fnscale=-1))


if (require(lme4)){
    fit1  <- lmer(wear ~ type + (1|boy), data=shoes_long)
    VarCorr(fit1)
    fixef(fit1)  
    ##yy <- shoes_long$wear
    ##XX <- getME(fit1, "X") |> head(10)
    ##ZZ <- getME(fit1, "Z") |> as.matrix()
}














structure(list(boy = structure(c(1L, 1L, 2L, 2L, 3L, 3L, 4L, 
4L), levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", 
"10"), class = "factor"), footA = c("L", "L", "L", "L", "R", 
"R", "L", "L"), type = c("A", "B", "A", "B", "A", "B", "A", "B"
), wear = c(13.2, 14, 8.2, 8.8, 10.9, 11.2, 14.3, 14.2)), row.names = c(NA, 
                                                                        -8L), class = c("tbl_df", "tbl", "data.frame"))

shoes_long <- structure(list(boy = structure(c(1L, 1L, 2L, 2L, 3L, 3L, 4L, 
4L), levels = c("1", "2", "3", "4", "5", "6", "7", "8", "9", 
"10"), class = "factor"), footA = c("L", "L", "L", "L", "R", 
"R", "L", "L"), type = c("A", "B", "A", "B", "A", "B", "A", "B"
), wear = c(13.2, 14, 8.2, 8.8, 10.9, 11.2, 14.3, 14.2)), row.names = c(NA, 
-8L), class = "data.frame")

library(caracas)
XX <- structure(c(1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1), dim = c(8L, 
2L), dimnames = list(c("1", "2", "3", "4", "5", "6", "7", "8"
), c("(Intercept)", "typeB")))

ZZ <- structure(c(1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 
0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1), dim = c(8L, 4L), dimnames = list(
    c("1", "2", "3", "4", "5", "6", "7", "8"), c("1", "2", "3", 
    "4")))

yy <- c(13.2, 14, 8.2, 8.8, 10.9, 11.2, 14.3, 14.2)






VV_func <- caracas::as_func(VV_)

## chol(VV_, hermitian=FALSE)
VV_func(.1, .3)



```

```{r}
Zu <- u <- as_sym(Z) %*% vector_sym(ncol(Z), "u")
Xb <- as_sym(X) %*% vector_sym(ncol(X), "b")
Mv(as_sym(X), "b")
a<- Mv2(as_sym(X), "b")
ss <- list(Xb, "+", Zu, "+", a) 
```





$$
`r tex_list(x=list(Xb, "+", Zu))` ## FIXME: Noget rod med navnet x
$$





```{r }
dat <- Orthodont[c(1:8,65:(65+7)),]

ort1 <- lmer(distance ~ age * Sex + (1|Subject), data=dat)
ort1 |> getME("Ztlist")
ort1 |> tidy()
VarCorr(ort1)
logLik(ort1)

ort2 <- lmer(distance ~ age * Sex + (age-1|Subject), data=dat)
ort2 |> getME("Ztlist")
ort2 |> tidy()
VarCorr(ort2)
logLik(ort2)

ort4 <- lmer(distance ~ age * Sex + (age|Subject), data=dat)
ort4 |> getME("Ztlist")
ort4 |> tidy()
VarCorr(ort4)
logLik(ort4)

ort5 <- lmer(distance ~ age * Sex + (age||Subject), data=dat)
ort5 |> getME("Ztlist")
ort5 |> tidy()
VarCorr(ort5)
logLik(ort5)

model.matrix(~-1+Subject, data=dat)
model.matrix(~-1+age:Subject, data=dat)

Zt5 <- ort5 |> getME("Ztlist")
```
